name: Deploy Todo App
concurrency: deploy-todo-app

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
    AZURE_RESOURCE_GROUP_NAME: TodoApp
    ENVIRONMENT: dev

# https://learn.microsoft.com/en-us/training/modules/test-bicep-code-using-github-actions/3-lint-validate-bicep-code?pivots=powershell

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Lint
      run: |
        az bicep build --file infrastructure/main.bicep    

  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Azure Login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    - name: Preflight validation
      uses: azure/arm-deploy@v1
      with:
        deploymentName: ${{ github.run_number }}
        scope: resourcegroup
        resourceGroupName: ${{ env.AZURE_RESOURCE_GROUP_NAME }}
        template: ./infrastructure/main.bicep
        parameters: >
          environmentType=${{ env.ENVIRONMENT }}
        deploymentMode: Validate #  preflight validation

  preview:
    runs-on: ubuntu-latest
    needs: [lint, validate]
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Azure Login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    - uses: azure/arm-deploy@v1
      name: Run what-if
      with:
        deploymentName: ${{ github.run_number }}
        scope: resourcegroup
        resourceGroupName: ${{ env.AZURE_RESOURCE_GROUP_NAME }}
        template: infrastructure/main.bicep
        parameters: >
          environmentType=${{ env.ENVIRONMENT }}
        additionalArguments: --what-if
        failOnStdErr: false

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [preview]
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Azure Login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    - name: Deploy
      uses: azure/arm-deploy@v1
      with:
        deploymentName: ${{ github.run_number }}
        scope: resourcegroup
        resourceGroupName: ${{ env.AZURE_RESOURCE_GROUP_NAME }}
        template: ./infrastructure/main.bicep
        parameters: >
          environmentType=${{ env.ENVIRONMENT }}
        failOnStdErr: false