name: Deploy Application

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      appServiceAppName:
          required: true
          type: string
    secrets:
      AZURE_CLIENT_ID:
        required: true
      AZURE_TENANT_ID:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true

jobs:
  deploy-application:
    name: Deploy application
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: application
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Deploy application
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ inputs.appServiceAppName }}
          package: publish.zip