name: Lint infrastructure

on:
  workflow_call:

jobs:
  lint:
    name: Lint infrastructure
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Lint infrastructure
      run: |
        az bicep build --file infra/main.bicep