
name: Deploy Todo App (E2E)

concurrency:
  group: todo-all-deploy
  cancel-in-progress: false

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

# https://learn.microsoft.com/en-us/training/modules/manage-end-end-deployment-scenarios-using-bicep-github-actions/3-configure-applications-virtual-machines

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml

  lint:
    name: Lint
    uses: ./.github/workflows/lint.yml

  deploy-test:
    name: Deploy [test]
    uses: ./.github/workflows/deploy.yml
    with:
      environment: test
      resourceGroupName: TodoAppTest
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    needs: [build, lint]

  deploy-production:
    name: Deploy [production]
    uses: ./.github/workflows/deploy.yml
    with:
      environment: production
      resourceGroupName: TodoAppProd
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    needs: [deploy-test]
