name: PR closed

concurrency:
  group: ${{ github.event.number }}
  cancel-in-progress: false

on:
  pull_request:
    branches:
      - main
    types: [closed]

permissions:
  id-token: write
  contents: read

env:
  resourceGroupName: pr_${{ github.event.number }}

jobs:
  delete-infra:
    name: Delete infrastructure
    runs-on: ubuntu-latest
    environment: test
    steps:
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Delete infrastructure
        uses: azure/cli@v2
        with:
          inlineScript: |
            az group delete \
              --name ${{ env.resourceGroupName }} \
              --yes